"""REQ-P8-003: frozen downstream-consumer acceptance contract.

ONE frozen acceptance test suite that simulates exactly what the downstream
host (``mcp-vfp9sp2-toolchain``) needs, WITHOUT importing, checking out or
otherwise depending on that host:

1. capability discovery through PUBLIC imports with recovery INDEPENDENTLY
   disabled by host policy (``RecoveryPolicy.DISABLED``);
2. pseudonymization and verification invoked through PUBLIC Python imports
   only (``import dbf_anonymizer`` — the package root, never a private
   ``dbf_anonymizer.*`` submodule);
3. an INJECTED, producer-independent external relationship/index metadata
   document (REQ-P6-006 contract) accepted through the PUBLIC planning
   boundary: explicit provenance, authority, assurance, normalized relative
   identities and at least one index claim with an explicit verification
   state;
4. a SYNTHETIC MULTI-TABLE dataset (the canonical REQ-P8-002 three-table
   fixture) with a declared PK/FK relation;
5. preserved declared PK/FK relations (truthful verification assurance and
   per-value join/bijection evidence through public reads — never inferred
   from row counts);
6. a CLEAN transferable DATA_ONLY bundle created and INDEPENDENTLY verified
   (source absent), with the forbidden recovery/secret/index material absent
   under the frozen 1.0 transfer-bundle contract.

The consumer requirements are FROZEN against the committed REQ-P8-001
snapshot ``contracts/public-contract-1.0.json``: any incompatible change to
a required consumer capability (root export, callable signature, recovery
policy vocabulary, external-metadata schema/resource/digest/vocabulary,
transfer-bundle surface) fails this suite.  No second snapshot is created
and no snapshot is ever regenerated by a failing test.

The dataset is 100% synthetic (written through the public ``dbfbridge``
writer); no production data, no network access, no MCP/server framework and
no real VFP runtime is involved.
"""

from __future__ import annotations

import ast
import hashlib
import json
import shutil
import sqlite3
from collections import Counter
from importlib import resources
from pathlib import Path
from typing import Any

import dbfbridge
import pytest

import dbf_anonymizer as public
from tests.test_p7_transport_boundary import FORBIDDEN_TRANSPORT_ROOTS, _import_roots
from tests.test_p8_contract_freeze import SNAPSHOT_PATH, _assert_frozen, build_contract
from tools.acceptance_fixtures import (
    BINARY_CANARIES,
    TEXT_CANARIES,
    write_dataset,
)

CONSUMER_PRODUCER_ID = "downstream-consumer-simulation"


class FrozenDownstreamConsumer:
    """The simulated transport-neutral downstream host adapter.

    The host exposes pseudonymization and verification while INDEPENDENTLY
    disabling recovery: the adapter's immutable local policy is
    ``RecoveryPolicy.DISABLED`` and its ``recover`` delegation can only ever
    produce the typed policy refusal.  Everything is called through the
    public package root; the host knows no private module and no transport
    framework.
    """

    def __init__(self) -> None:
        self._recovery_policy = public.RecoveryPolicy.DISABLED

    def capabilities(self) -> public.Capabilities:
        return public.capabilities(self._recovery_policy)

    def build_plan(
        self,
        source: Path,
        output: Path,
        vault: Path,
        *,
        relationship_document: dict[str, Any] | None = None,
    ) -> public.Plan:
        return public.build_plan(
            source,
            output,
            vault,
            relationship_document=relationship_document,
        )

    def pseudonymize(self, plan: public.Plan, *, workers: int = 1) -> public.PseudonymizationResult:
        return public.pseudonymize(plan, workers=workers)

    def verify_dataset(
        self,
        result: public.PseudonymizationResult,
        *,
        source: Path,
        vault: Path,
    ) -> public.VerificationResult:
        return public.verify_dataset(result, source=source, vault=vault)

    def create_transfer_bundle(
        self,
        result: public.PseudonymizationResult,
        *,
        destination: Path,
        profile: str,
    ) -> public.TransferBundleResult:
        return public.create_transfer_bundle(result, destination=destination, profile=profile)

    def verify_transfer_bundle(self, bundle: Path) -> public.TransferBundleResult:
        return public.verify_transfer_bundle(bundle)

    def recover(self, pseudonymized: Path, *, vault: Path, output: Path) -> public.RecoveryResult:
        return public.recover(
            pseudonymized,
            vault=vault,
            output=output,
            recovery_policy=self._recovery_policy,
        )


def _shipped_external_schema() -> dict[str, Any]:
    """The shipped JSON Schema through the documented public resource path."""
    snapshot = _frozen_snapshot()
    resource = str(snapshot["relationships"]["external_metadata"]["schema_resource"])
    text = resources.files("dbf_anonymizer").joinpath(resource).read_text(encoding="utf-8")
    return json.loads(text)


def _frozen_snapshot() -> dict[str, Any]:
    return json.loads(SNAPSHOT_PATH.read_text(encoding="ascii"))


def _consumer_document() -> dict[str, Any]:
    """The producer-independent external metadata document (REQ-P6-006).

    Version/vocabulary values are taken from the FROZEN 1.0 contract and the
    shipped JSON Schema resource — no stale duplicated literals.
    """
    snapshot = _frozen_snapshot()
    relationships = snapshot["relationships"]
    external = relationships["external_metadata"]
    schema = _shipped_external_schema()
    assert schema["x-contract-schema-version"] == external["schema_version"]
    assert "EXTERNAL_VFP_METADATA" in relationships["provenances"]
    assert "CONTRACT_AUTHORITATIVE" in external["claim_authorities"]
    assert "VERIFIED" in external["claim_assurances"]
    assert "VERIFIED" in external["index_verification_states"]
    assert "STRUCTURAL_CDX" in external["index_kinds"]
    return {
        "metadata_schema_version": relationships["metadata_schema_version"],
        "external_metadata_schema_version": external["schema_version"],
        "producer": {"producer_id": CONSUMER_PRODUCER_ID, "producer_version": "1.0.0"},
        "authority": "CONTRACT_AUTHORITATIVE",
        "relations": [
            {
                "relation_id": "north-south-code-fk",
                "comparison": "EXACT_VALUE",
                "provenance": "EXTERNAL_VFP_METADATA",
                "assurance": "VERIFIED",
                "authority": "CONTRACT_AUTHORITATIVE",
                "members": [
                    {
                        "table": "north/data.dbf",
                        "field": "CODE",
                        "role": "PRIMARY",
                        "ordinal": 1,
                        "dbf_type": "C",
                        "byte_width": 12,
                        "encoding": "cp1250",
                        "nullable": True,
                    },
                    {
                        "table": "south/data.dbf",
                        "field": "CODE",
                        "role": "FOREIGN",
                        "ordinal": 1,
                        "dbf_type": "C",
                        "byte_width": 12,
                        "encoding": "cp1250",
                        "nullable": True,
                    },
                ],
            }
        ],
        "index_claims": [
            {
                "claim_id": "north-code-structural-cdx",
                "table": "north/data.dbf",
                "index_file": "north/data.cdx",
                "index_kind": "STRUCTURAL_CDX",
                "tags": [{"name": "CODE", "sort_order": "ASCENDING", "expression": "CODE"}],
                "verification_state": "VERIFIED",
                "assurance": "VERIFIED",
                "provenance": "EXTERNAL_VFP_METADATA",
                "authority": "CONTRACT_AUTHORITATIVE",
            }
        ],
    }


def _code_column(root: Path, relative: str) -> tuple[tuple[int, bool, object], ...]:
    """The per-record (physical_index, deleted, CODE) column through public reads."""
    return tuple(
        (record.physical_index, record.deleted, record.values.get("CODE"))
        for record in dbfbridge.iter_records(  # type: ignore[attr-defined]
            root / relative, include_deleted=True, memo="inline"
        )
    )


def _assert_pk_fk_preserved(source: Path, output: Path) -> None:
    """Objective declared PK/FK preservation through public reads only.

    The declared relation is north/data.dbf CODE (PRIMARY) ->
    south/data.dbf CODE (FOREIGN).  The evidence is per-value, not row
    counts: the FK join stays valid, distinct originals stay bijective and
    every transformed member value is a genuine pseudonym.
    """
    parent_before = _code_column(source, "north/data.dbf")
    child_before = _code_column(source, "south/data.dbf")
    parent_after = _code_column(output, "north/data.dbf")
    child_after = _code_column(output, "south/data.dbf")

    assert [row[0] for row in parent_before] == [row[0] for row in parent_after]
    assert [row[1] for row in parent_before] == [row[1] for row in parent_after]
    assert [row[1] for row in child_before] == [row[1] for row in child_after]

    parent_by_index = {row[0]: row for row in parent_after}
    child_by_index = {row[0]: row for row in child_after}

    parent_originals = {row[2]: row[0] for row in parent_before if row[2]}
    assert len(parent_originals) == 2
    pseudonym_by_original = {}
    for original, index in parent_originals.items():
        pseudonym = parent_by_index[index][2]
        assert pseudonym != original
        assert isinstance(pseudonym, str) and pseudonym.strip() != ""
        pseudonym_by_original[original] = pseudonym
    assert len(set(pseudonym_by_original.values())) == len(pseudonym_by_original)

    join_before = [row[2] for row in child_before if row[2]]
    assert join_before == ["PARENT-1"]
    child_joined = [row for row in child_after if row[2]]
    assert len(child_joined) == 1
    assert child_joined[0][2] == pseudonym_by_original["PARENT-1"]

    assert parent_by_index[0][1] is False
    assert parent_by_index[1][1] is True
    assert child_by_index[0][1] is True
    assert child_by_index[1][1] is False
    assert child_by_index[1][2] is None


def _assert_clean_data_only_bundle(
    bundle: Path, frozen: dict[str, Any], consumer_result: public.TransferBundleResult
) -> tuple[list[str], bool]:
    """The bundle content scan under the FROZEN 1.0 transfer-bundle contract."""
    contract = frozen["transfer_bundle"]
    files = [
        path.relative_to(bundle).as_posix() for path in sorted(bundle.rglob("*")) if path.is_file()
    ]
    manifest_filename = str(contract["manifest_filename"])
    allowed_suffixes = {"." + str(item).lower() for item in contract["allowed_artifact_classes"]}
    allowlist_ok = all(
        name == manifest_filename or Path(name).suffix.lower() in allowed_suffixes for name in files
    )
    forbidden_suffixes = {str(item) for item in contract["forbidden_suffixes"]}
    forbidden_markers = {str(item) for item in contract["forbidden_basename_markers"]}
    forbidden_absent = not any(
        Path(name).suffix in forbidden_suffixes
        or any(marker in name.lower() for marker in forbidden_markers)
        for name in files
    )
    canaries_absent = not any(
        canary.encode("utf-8") in path.read_bytes()
        for path in bundle.rglob("*")
        if path.is_file()
        for canary in TEXT_CANARIES
    ) and not any(
        canary in path.read_bytes()
        for path in bundle.rglob("*")
        if path.is_file()
        for canary in BINARY_CANARIES
    )
    assert allowlist_ok is True
    assert forbidden_absent is True
    assert canaries_absent is True
    assert consumer_result.profile is public.TransferProfile.DATA_ONLY
    assert consumer_result.verified is True
    assert files
    assert any(name.endswith(".dbf") for name in files)
    assert any(name.endswith(".fpt") for name in files)
    return files, canaries_absent


def test_downstream_consumer_capabilities_with_recovery_independently_disabled() -> None:
    """The host discovers its consumer-facing capability set with recovery
    disabled by ITS OWN policy: pseudonymization, verification and the
    transfer bundle remain available while recovery is refused."""
    consumer = FrozenDownstreamConsumer()
    disabled = consumer.capabilities()
    assert disabled.recovery is False
    assert disabled.direct_read is True
    assert disabled.direct_write is True
    assert disabled.transfer_bundle is True
    assert disabled.vfp_index_backend is False
    assert disabled.dbfbridge_version
    enabled = public.capabilities(public.RecoveryPolicy.ENABLED)
    assert enabled.recovery is True
    assert disabled.direct_read == enabled.direct_read
    assert disabled.direct_write == enabled.direct_write
    assert disabled.transfer_bundle == enabled.transfer_bundle
    assert disabled.dbfbridge_version == enabled.dbfbridge_version
    assert tuple(public.RecoveryPolicy) == (
        public.RecoveryPolicy.ENABLED,
        public.RecoveryPolicy.DISABLED,
    )
    assert json.dumps(disabled.to_dict())


def test_frozen_downstream_consumer_acceptance_workflow(tmp_path: Path) -> None:
    """THE frozen downstream-consumer acceptance workflow (REQ-P8-003).

    capabilities(disabled) -> build_plan(injected external metadata) ->
    preflight -> pseudonymize -> verify_dataset -> create_transfer_bundle
    (DATA_ONLY) -> standalone verify_transfer_bundle (source absent) ->
    recover refused under the independently disabled host policy — the whole
    workflow through PUBLIC imports only, on the synthetic multi-table
    PK/FK dataset.
    """
    consumer = FrozenDownstreamConsumer()
    document = _consumer_document()

    source = tmp_path / "source"
    write_dataset(source)
    output = tmp_path / "output"
    vault = tmp_path / "vault" / "dictionary.sqlite3"

    plan = consumer.build_plan(source, output, vault, relationship_document=document)
    assert isinstance(plan, public.Plan)
    relationships = plan.relationships
    assert relationships.provenance == "EXTERNAL_VFP_METADATA"
    assert relationships.relation_count == 1
    assert relationships.authoritative is True
    assert relationships.producer_id == CONSUMER_PRODUCER_ID
    execution_context = plan.execution_context
    assert execution_context is not None
    external_document = execution_context.relationship_document
    index_claims = external_document.index_claims
    assert len(index_claims) == 1
    assert index_claims[0].verification_state == "VERIFIED"
    assert index_claims[0].verified is True
    assert external_document.verified_index_claims() == (index_claims[0],)
    assert plan.relationship_assurance_target is (
        public.RelationalAssuranceLevel.DECLARED_RELATIONS_VERIFIED
    )

    preflight_result = public.preflight(plan)
    assert isinstance(preflight_result, public.PreflightResult)
    assert preflight_result.ready is True

    result = consumer.pseudonymize(plan, workers=2)
    assert isinstance(result, public.PseudonymizationResult)
    _assert_pk_fk_preserved(source, output)
    output_blob = b"".join(
        path.read_bytes() for path in sorted(output.rglob("*")) if path.is_file()
    )
    for canary in TEXT_CANARIES:
        assert canary.encode("utf-8") not in output_blob
    for canary in BINARY_CANARIES:
        assert canary not in output_blob

    verification = consumer.verify_dataset(result, source=source, vault=vault)
    assert isinstance(verification, public.VerificationResult)
    assert verification.status is public.VerificationStatus.PASS
    assert verification.assurance.level is public.RelationalAssuranceLevel.VFP_METADATA_VERIFIED
    assert verification.assurance.declared_relations == 1
    assert verification.assurance.verified_relations == 1
    assert verification.assurance.failed_relations == 0
    assert verification.assurance.relationship_fingerprint == (
        relationships.relationship_fingerprint
    )

    bundle = consumer.create_transfer_bundle(
        result, destination=tmp_path / "bundle", profile="DATA_ONLY"
    )
    assert isinstance(bundle, public.TransferBundleResult)
    copied = tmp_path / "copied-bundle"
    shutil.copytree(tmp_path / "bundle", copied)
    shutil.rmtree(source)
    standalone = consumer.verify_transfer_bundle(copied)
    assert standalone.verified is True
    assert standalone.manifest_fingerprint == bundle.manifest_fingerprint

    files, canaries_absent = _assert_clean_data_only_bundle(
        tmp_path / "bundle", _frozen_snapshot(), bundle
    )
    assert canaries_absent is True
    assert files

    vault_directory = vault.parent
    vault_files_before = tuple(sorted(path.name for path in vault_directory.iterdir()))
    calls: Counter[str] = Counter()

    def forbidden_sqlite(*args: object, **kwargs: object) -> Any:
        calls["sqlite_connect"] += 1
        raise AssertionError("disabled recovery opened SQLite")

    recovered = tmp_path / "recovered"
    with pytest.MonkeyPatch.context() as patch:
        patch.setattr(sqlite3, "connect", forbidden_sqlite)
        with pytest.raises(public.RecoveryError) as caught:
            consumer.recover(output, vault=vault, output=recovered)
    assert calls == Counter()
    assert caught.value.code is public.ErrorCode.RECOVERY_NOT_PERMITTED
    assert caught.value.context.detail_code == "POLICY_DISABLED"
    serialized = json.dumps(caught.value.to_dict(), sort_keys=True)
    assert str(vault.resolve()) not in serialized
    assert not recovered.exists()
    assert not tuple(tmp_path.glob("*.staging"))
    assert tuple(sorted(path.name for path in vault_directory.iterdir())) == vault_files_before


def test_downstream_consumer_contract_file_imports_only_the_public_root() -> None:
    """The simulated consumer boundary imports ONLY the public package root:
    no private ``dbf_anonymizer.*`` submodule, no MCP/server/transport
    framework, no async surface."""
    source = Path(__file__).read_text(encoding="utf-8")
    tree = ast.parse(source)
    dbf_imports: list[str] = []
    public_attributes: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                if alias.name.startswith("dbf_anonymizer"):
                    dbf_imports.append(alias.name)
        elif isinstance(node, ast.ImportFrom):
            if (node.module or "").startswith("dbf_anonymizer"):
                dbf_imports.append(node.module or "")
        elif (
            isinstance(node, ast.Attribute)
            and isinstance(node.value, ast.Name)
            and node.value.id == "public"
        ):
            public_attributes.add(node.attr)
    assert dbf_imports == ["dbf_anonymizer"]
    assert public_attributes <= set(getattr(public, "__all__"))
    assert not (_import_roots(source) & FORBIDDEN_TRANSPORT_ROOTS)
    assert not any(isinstance(node, (ast.AsyncFunctionDef, ast.Await)) for node in ast.walk(tree))


def test_downstream_consumer_requirements_are_frozen_in_the_public_contract() -> None:
    """The downstream consumer requirements are FROZEN by the committed
    REQ-P8-001 1.0 snapshot: every required consumer capability must exist
    in the frozen contract, and the frozen contract must still equal the
    actual public surface.  No second snapshot and no regeneration."""
    frozen = _frozen_snapshot()
    _assert_frozen(build_contract(), frozen)

    exports = set(frozen["python_api"]["root_exports"])
    required_exports = {
        "capabilities",
        "build_plan",
        "preflight",
        "pseudonymize",
        "verify_dataset",
        "recover",
        "create_transfer_bundle",
        "verify_transfer_bundle",
        "RecoveryPolicy",
        "RecoveryError",
        "ErrorCode",
        "Capabilities",
        "Plan",
        "PreflightResult",
        "PseudonymizationResult",
        "VerificationResult",
        "VerificationStatus",
        "RelationalAssurance",
        "RelationalAssuranceLevel",
        "RelationshipMetadata",
        "TransferBundleResult",
        "TransferProfile",
    }
    assert required_exports <= exports

    callables = frozen["python_api"]["callables"]
    required_parameters = {
        "build_plan": ("source", "output", "vault", "policy", "relationship_document"),
        "pseudonymize": ("plan", "workers"),
        "preflight": ("plan",),
        "verify_dataset": ("result", "source", "vault"),
        "recover": ("pseudonymized", "vault", "output", "recovery_policy"),
        "create_transfer_bundle": ("result", "destination", "profile"),
        "verify_transfer_bundle": ("bundle",),
        "capabilities": ("recovery_policy",),
    }
    for name, parameter_names in required_parameters.items():
        parameters = {parameter["name"] for parameter in callables[name]["parameters"]}
        assert set(parameter_names) <= parameters, name

    assert frozen["public_json"]["enums"]["RecoveryPolicy"] == ["enabled", "disabled"]

    relationships = frozen["relationships"]
    external = relationships["external_metadata"]
    shipped_schema = _shipped_external_schema()
    assert external["schema_version"] == shipped_schema["x-contract-schema-version"]
    shipped_resource = str(external["schema_resource"])
    shipped_text = resources.files("dbf_anonymizer").joinpath(shipped_resource).read_text("utf-8")
    shipped_schema = json.loads(shipped_text)
    canonical = json.dumps(
        shipped_schema, sort_keys=True, separators=(",", ":"), ensure_ascii=True
    ).encode("ascii")
    assert external["schema_sha256"] == hashlib.sha256(canonical).hexdigest()
    assert external["producer_independent"] is True
    assert "EXTERNAL_VFP_METADATA" in relationships["provenances"]
    assert {"CONTRACT_AUTHORITATIVE"} <= set(external["claim_authorities"])
    assert {"VERIFIED"} <= set(external["claim_assurances"])
    assert {"VERIFIED"} <= set(external["index_verification_states"])
    assert {"STRUCTURAL_CDX"} <= set(external["index_kinds"])
    assert relationships["metadata_schema_version"] == "1.0"
    assert {"DECLARED_RELATIONS_VERIFIED", "VFP_METADATA_VERIFIED"} <= set(
        relationships["assurance_levels"]
    )

    transfer = frozen["transfer_bundle"]
    assert transfer["profile"] == "DATA_ONLY"
    assert transfer["schema_version"] == "1.1"
    assert transfer["manifest_filename"] == "transfer-manifest.json"
    assert transfer["allowed_artifact_classes"] == ["DBF", "FPT"]
    assert {".cdx", ".idx", ".dbc", ".sqlite3", ".sqlite3-wal", "-wal", "-shm", ".journal"} <= set(
        transfer["forbidden_suffixes"]
    )
    assert {"dictionary.sqlite", "recovery", "reverse-mapping", "secret", "salt"} <= set(
        transfer["forbidden_basename_markers"]
    )
    assert {
        "SQLITE_VAULT_AND_WAL_SHM_JOURNAL",
        "RECOVERY_MAPPINGS_AND_MATERIAL",
        "SECRETS_AND_ORIGINAL_VALUES",
        "STALE_OR_UNVERIFIED_CDX_IDX_DBC_DCT_DCX",
    } <= set(transfer["forbidden_material"])
    assert {"DATA_ONLY_INDEX_OMITTED"} <= set(transfer["index_states"])

    assert frozen["package_version_status"] == "1.0.0.dev0"


def test_downstream_consumer_refuses_before_vault_access_without_any_vault(
    tmp_path: Path,
) -> None:
    """The disabled consumer-facing recovery refusal precedes ALL validation
    and access: with a MISSING vault and a MISSING pseudonymized dataset the
    typed refusal is still exactly POLICY_DISABLED (never a path error), no
    SQLite connection is attempted and nothing is created."""
    consumer = FrozenDownstreamConsumer()
    calls: Counter[str] = Counter()

    def forbidden_sqlite(*args: object, **kwargs: object) -> Any:
        calls["sqlite_connect"] += 1
        raise AssertionError("disabled recovery opened SQLite")

    output = tmp_path / "recovered"
    with pytest.MonkeyPatch.context() as patch:
        patch.setattr(sqlite3, "connect", forbidden_sqlite)
        with pytest.raises(public.RecoveryError) as caught:
            consumer.recover(
                tmp_path / "missing-pseudonymized",
                vault=tmp_path / "missing-private-vault.sqlite",
                output=output,
            )
    assert calls == Counter()
    assert caught.value.code is public.ErrorCode.RECOVERY_NOT_PERMITTED
    assert caught.value.context.detail_code == "POLICY_DISABLED"
    assert not output.exists()
